[project]
name = "memory-chain"
version = "0.1.0"
src = "src"
out = "out"
dot_env = ".env"

[compiler]
evm_version = "cancun"

[networks.base-sepolia]
url = "$BASE_SEPOLIA_RPC"
chain_id = 84532
default_account_name = "deployer_account"
prompt_live = true
explorer_uri = "https://api-sepolia.basescan.org/api"
explorer_type = "etherscan"
explorer_api_key = "$BASESCAN_API_KEY"

[networks.base]
url = "$BASE_MAINNET_RPC"
chain_id = 8453
default_account_name = "deployer_account"
prompt_live = true
explorer_uri = "https://api.basescan.org/api"
explorer_type = "etherscan"
explorer_api_key = "$BASESCAN_API_KEY"