"""
script/export_artifacts.py
Автономный генератор артефактов (ABI + Адреса + Константы) для фронтенда.
Работает как через `mox run script/export_artifacts.py`, так и через `python script/export_artifacts.py`.
"""

import json
import sys
from pathlib import Path
import boa

# 1. Корректная привязка корня проекта независимо от директории вызова
PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_DIR = PROJECT_ROOT / "deployments" / "artifacts"

DEPLOYMENT_METADATA = {
    "network": "base-sepolia",
    "chainId": 84532,
    "rpcUrl": "https://sepolia.base.org",
    "blockExplorer": "https://sepolia.basescan.org",
    "contracts": {
        "MemoryChainCore": {
            "address": "0x5de836cf6fc88d88eec93309663372ad723baf8f",
        },
        "ModerationModule": {
            "address": "0x7120f05831bab3742b58a0a17e7a9b64789f30f3",
        },
        "SafeMultisig": {
            "address": "0x7D29Ae44D5041b59012e784818446088774305F5",
            "role": "Owner & Treasury (Совет Хранителей)",
        },
    },
    "protocolConstants": {
        "CANDLE_PRICE_WEI": "100000000000000",  # 0.0001 ETH
        "CREATION_FEE_WEI": "100000000000000",  # 0.0001 ETH
        "TIMELOCK_DELAY_SECONDS": 172800,  # 48 часов
    },
}


def export():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # Компиляция контрактов напрямую через Titanoboa без вызова конструктора
    core_path = PROJECT_ROOT / "src" / "MemoryChainCore.vy"
    mod_path = PROJECT_ROOT / "src" / "ModerationModule.vy"

    print(f"[*] Компиляция {core_path.name}...")
    core_deployer = boa.load_partial(str(core_path))
    #core_abi = core_deployer.abi
    core_abi = core_deployer.compiler_data.abi

    print(f"[*] Компиляция {mod_path.name}...")
    mod_deployer = boa.load_partial(str(mod_path))
    mod_abi = mod_deployer.abi

    # 1. Запись ABI Core
    with open(OUTPUT_DIR / "MemoryChainCore.json", "w", encoding="utf-8") as f:
        json.dump(core_abi, f, indent=2)
    print(f"[✓] Создан: {OUTPUT_DIR / 'MemoryChainCore.json'}")

    # 2. Запись ABI ModerationModule
    with open(OUTPUT_DIR / "ModerationModule.json", "w", encoding="utf-8") as f:
        json.dump(mod_abi, f, indent=2)
    print(f"[✓] Создан: {OUTPUT_DIR / 'ModerationModule.json'}")

    # 3. Запись конфигурационного манифеста
    with open(OUTPUT_DIR / "base-sepolia.json", "w", encoding="utf-8") as f:
        json.dump(DEPLOYMENT_METADATA, f, indent=2)
    print(f"[✓] Создан: {OUTPUT_DIR / 'base-sepolia.json'}")

    # 4. TypeScript модуль для Wagmi/Viem
    ts_code = f"""// Auto-generated by script/export_artifacts.py
export const BASE_SEPOLIA_CHAIN_ID = 84532 as const;

export const CONTRACT_ADDRESSES = {{
  core: "{DEPLOYMENT_METADATA['contracts']['MemoryChainCore']['address']}",
  moderationModule: "{DEPLOYMENT_METADATA['contracts']['ModerationModule']['address']}",
  councilSafe: "{DEPLOYMENT_METADATA['contracts']['SafeMultisig']['address']}",
}} as const;

export const CORE_ABI = {json.dumps(core_abi, indent=2)} as const;
export const MODERATION_ABI = {json.dumps(mod_abi, indent=2)} as const;
"""
    with open(OUTPUT_DIR / "contracts.ts", "w", encoding="utf-8") as f:
        f.write(ts_code)
    print(f"[✓] Создан: {OUTPUT_DIR / 'contracts.ts'}")


def moccasin_main():
    export()


if __name__ == "__main__":
    export()